### PR TITLE
fix(diagnostics): throttle sequential CocDiagnostics updates, make debouncer safe and sequential

### LINKED ISSUE #1317: [coc.nvim] Error on request (diagnosticList)
### Description

```
Error on request (diagnosticList): Vim(return):Error invoking 'diagnosticList' on channel 3 (coc):                                                                                                   
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
```
After that, coc.nvim loses connection to language server

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 5.17.9-zen1-1-zen

### nvim-tree version

25921aa

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      {"neoclide/coc.nvim", branch = "release"}
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    diagnostics = {enable=true, show_on_dirs=true}
  }
end
```

### Steps to reproduce

1. :NvimTreeOpen
2. :CocInstall rust-analyzer to replicate how I do it
3. Open a file that contains coc.nvim diagnostics. For example, `src/prototypes/mod.rs` in https://github.com/JohnTheCoolingFan/factorio-lib-rs
4. Wait for error to occur

### Expected behavior

_No response_

### Actual behavior

_No response_

### PR DESCRIPTION
**Pull request by alex-courtis**
closes #1317 

This took way too long...

1. debouncer is "safe"
2. debouncer reschedules while previous job is excuting

2 could be optional, however it suits all our current use cases including git "threads". We can add an option later if we need it.

Tested:
* COC with the incredible number of events that https://github.com/kyazdani42/nvim-tree.lua/issues/1317 produces
* heavy, concurrent git operations e.g. `rm .git/touched* builddefs/touched* docs/touched* ; for i in $(seq 1 200); do touch .git/touched$i; touch builddefs/touched$i; touch docs/touched$i; done`

Did not test LSP; COC testing should be sufficient.

### CODE REVIEW

File: lua/nvim-tree/utils.lua [hunk 1]
```diff
@@ -307,25 +307,57 @@ function M.key_by(tbl, key)
...
+---Invocation will be rescheduled while a callback is being executed.
+---Caller must ensure that callback performs the same or functionally equivalent actions.
+---
 ---@param context string identifies the callback to debounce
 ---@param timeout number ms to wait
 ---@param callback function to execute on completion
 function M.debounce(context, timeout, callback)
-  if M.debouncers[context] then
-    pcall(uv.close, M.debouncers[context])
+  -- all execution here is done in a synchronous context; no thread safety required
```
Comment (alex-courtis) [inline lua/nvim-tree/utils.lua:328]: tested exhaustively using `vim.is_thread()`

File: lua/nvim-tree/utils.lua [hunk 2]
```diff
@@ -307,25 +307,57 @@ function M.key_by(tbl, key)
...
-  M.debouncers[context] = uv.new_timer()
-  M.debouncers[context]:start(
-    timeout,
-    0,
-    vim.schedule_wrap(function()
-      M.debouncers[context]:close()
-      M.debouncers[context] = nil
+  local timer = uv.new_timer()
+  debouncer.timer = timer
+  timer:start(timeout, 0, function()
```
Comment (alex-courtis) [inline lua/nvim-tree/utils.lua:340]: This is the key change: perform all our control operations in the direct callback instead of during scheduled execution.

File: lua/nvim-tree/utils.lua [hunk 3]
```diff
@@ -307,25 +307,57 @@ function M.key_by(tbl, key)
   return keyed
 end
 
----Execute callback timeout ms after the lastest invocation with context. Waiting invocations for that context will be discarded. Caller should this ensure that callback performs the same or functionally equivalent actions.
+local function timer_stop_close(timer)
+  if timer:is_active() then
+    timer:stop()
+  end
+  if not timer:is_closing() then
+    timer:close()
```
Comment (alex-courtis) [inline lua/nvim-tree/utils.lua:315]: Manual reference count handling was not necessary; libuv will clear the last reference on handle close.

File: lua/nvim-tree/git/init.lua [hunk 4]
```diff
@@ -138,10 +138,6 @@ function M.load_project_status(cwd)
           reload_tree_at(opts.project_root)
         end)
       end,
-      on_event0 = function()
```
Comment (alex-courtis) [inline lua/nvim-tree/git/init.lua:141]: I must have left this in when testing.

File: doc/nvim-tree-lua.txt [hunk 5]
```diff
@@ -888,6 +894,10 @@ Configuration for diagnostic logging.
         File copy and paste actions.
           Type: `boolean`, Default: `false`
 
+        *nvim-tree.log.types.dev*
```
Comment (alex-courtis) [inline doc/nvim-tree-lua.txt:897]: I keep needing a "clean" log context that doesn't get removed by `validate_options`. Feel free to remove.

**Review by kyazdani42 — APPROVED** [review]
