### PR TITLE
fix(view): Fix error thrown when trying to wipe buffer in autocmd window.

### LINKED ISSUE #309: Conflitcs with :mksession
**Steps to reproduce**

```vim
:mksession test.vim
:source test.vim
```

**Current result**

Session loaded with the following error:

```
|| Error detected while processing SessionLoadPost Autocommands for "*":
|| E5108: Error executing lua ...im/pack/plugins/opt/nvim-tree.lua/lua/nvim-tree/view.lua:92: Vim:E813: Cannot close autocmd window
```

**Expected result**

Session loaded without any errors.

### PR DESCRIPTION
**Pull request by sindrets**
Fixes #309.

### CODE REVIEW

File: lua/nvim-tree/view.lua [hunk 1]
```diff
@@ -89,9 +89,13 @@ function M._wipe_rogue_buffer()
...
     for _, id in ipairs(win_ids) do
-      a.nvim_win_close(id, true)
+      if vim.fn.win_gettype(id) ~= "autocmd" then
+        a.nvim_win_close(id, true)
+      end
     end
-    a.nvim_buf_delete(bn, {})
+    -- Do not use `nvim_buf_delete` here as it throws an uncacthable error if
+    -- the buffer is in an autocmd window.
+    a.nvim_command("silent! bw " .. bn)
```
Comment (sindrets) [inline lua/nvim-tree/view.lua:98]: I guess the reason its not caught by `pcall` is that the window isn't closed directly as a consequence of `nvim_buf_delete`, but vim tries to close it because we delete the last buffer in the window. Maybe upstream bug?

File: lua/nvim-tree/view.lua [hunk 2]
```diff
@@ -68,9 +68,9 @@ M.View = {
 ---Find a rogue NvimTree buffer that might have been spawned by i.e. a session.
 ---@return integer|nil
 local function find_rogue_buffer()
-  for i = 1, vim.fn.bufnr("$"), 1 do
-    if vim.fn.bufname(i) == "NvimTree" then
-      return i
+  for _, v in ipairs(a.nvim_list_bufs()) do
+    if vim.fn.bufname(v) == "NvimTree" then
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:72]: you can also use `a.nvim_buf_get_name(v)` i think :)

File: lua/nvim-tree/view.lua (hunk 1 above)
Comment (kyazdani42) [reply lua/nvim-tree/view.lua:98]: did you try to schedule the buf_delete call ?

Comment (sindrets) [reply lua/nvim-tree/view.lua]: Good call, scheduling seems to work quite well!

File: lua/nvim-tree/view.lua (hunk 2 above)
Comment (sindrets) [reply lua/nvim-tree/view.lua:72]: `nvim_buf_get_name` returns a path, so I thought this was cleaner.

File: lua/nvim-tree/view.lua (hunk 1 above)
Comment (kyazdani42) [reply lua/nvim-tree/view.lua]: yep, because it'll send the command in the event loop, thus all the other synchronous stuff must be done before triggering this :)
