### PR TITLE
fix(#1356): view.close switch_buf_if_last_buf prefers alt buf

### LINKED ISSUE #1356: Closing nvim-tree in vinegar mode will switch to first buffer
### Description

When opening nvim-tree in vinegar mode (via `open_replacing_current_buffer()`), closing the tree (via `q`) will switch the buffer to the first buffer.

You can simply open three buffers, open the third buffer (when inspecting via `:buffers`, you should be in the third), and then you should go into the tree with the config below.

Currently, I simply mapping a closing command like this:

```lua
local function close_tree()
    vim.cmd [[ buffer # ]]
end

local list = {
    ...
    { key = 'q', action = 'close_tree', action_cb = close_tree },
}

nvim_tree.setup {
    ...
    view = {
        mappings = {
            list = list,
        },
    },
}
```

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
```

### Operating system and version

macOS 12.4

### nvim-tree version

bdb6d4a

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
  function toggle_replace()
      local view = require 'nvim-tree.view'
      if view.is_visible() then
          view.close()
      else
          require('nvim-tree').open_replacing_current_buffer()
      end
  end

  vim.keymap.set('n', '-', toggle_replace)
end
```

### Steps to reproduce

1. nvim -nu /tmp/nvt-min.lua ./fileA
2. Press <kbd>-</kbd>, and open ./fileB
3. Press <kbd>-</kbd>, and then <kbd>q</kbd>

### Expected behavior

fileB is open

### Actual behavior

fileA is open

### PR DESCRIPTION
**Pull request by alex-courtis**
closes #1356 

Use `#` if available when closing last buf, falling back to next as per previous behaviour.

### CODE REVIEW

**Comment by hgiesel** [comment]
This works for me

File: lua/nvim-tree/view.lua [hunk 1]
```diff
@@ -130,16 +130,29 @@ local function open_window()
...
+  for _, buf in ipairs(a.nvim_list_bufs()) do
+    if a.nvim_buf_is_valid(buf) and vim.fn.buflisted(buf) == 1 then
+      next_buf = next_buf or buf
+      if buf == alt_bufnr then
+        alt_buf = buf
+      end
+    end
+  end
+
+  return alt_buf or next_buf
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:148]: The logic could be greatly simplified:
- check at the start that alt_bufnr is valid and listed, and return it in that case (create a small function like is_buf_displayed or something like that).
- then do the loop and return whenever you find a valid buffer

Comment (alex-courtis) [reply lua/nvim-tree/view.lua]: nice

**Review by kyazdani42 — APPROVED** [review]
