### PR TITLE
fix(#1533): make `toggle_mark` ignore non-togglable nodes.

### LINKED ISSUE #1533: `toggle_mark` on root node throws exception
### Description

`toggle_mark` (press `m`) on the tree's root node throws an exception.

### Neovim version

```text
NVIM v0.8.0-dev-878-g02e9b5a8e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.15.0-46-generic

### nvim-tree version

81eb718394e489d2aebbffa730d2517d72ec7f9c

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. `nvim -nu nvt-min.lua`
2. `:NvimTreeToggle`
3. Move cursor to the first node in the nvim-tree pane and press `m` to set a mark.

### Expected behavior

Nothing should happen.

### Actual behavior

Exception thrown:
```
E5108: Error executing lua: .../packer/start/nvim-tree.lua/lua/nvim-tree/marks/init.lua:10: table index is nil
stack traceback:
        .../packer/start/nvim-tree.lua/lua/nvim-tree/marks/init.lua:10: in function 'add_mark'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/marks/init.lua:23: in function 'handle_tree_actions'
        ...r/start/nvim-tree.lua/lua/nvim-tree/actions/dispatch.lua:120: in function 'dispatch'
        ...acker/start/nvim-tree.lua/lua/nvim-tree/actions/init.lua:260: in function <...acker/start/nvim-tree.lua/lua/nvim-tree/actions/init.lua:259>
```

### PR DESCRIPTION
**Pull request by sebcode**
resolves #1533

### CODE REVIEW

**Comment by alex-courtis** [comment]
Thanks for all these fixes!

File: lua/nvim-tree/marks/init.lua [hunk 1]
```diff
@@ -17,6 +17,10 @@ local function remove_mark(node)
 end
 
 function M.toggle_mark(node)
+  if node.absolute_path == nil then
```
Comment (alex-courtis) [inline lua/nvim-tree/marks/init.lua:20]: simpler than `is_root_folder_visible`

**Review by alex-courtis — APPROVED** [review]
tested:
`hide_root_folder` true/false
first, second, last nodes
