### PR TITLE
1221 handle deprecated vert split

### LINKED ISSUE #1221: call NvimTreeToggle, Invalid parameter
### Description

When I call NvimTreeToggle, I get an error

image

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.2.3

### nvim-tree version

86d573d

### Steps to reproduce

:NvimTreeToggle

### Expected behavior

_No response_

### Actual behavior

_No response_

### Minimal config

```Lua
-- init.lua
vim.o.ignorecase=true

vim.opt.encoding="UTF-8"
vim.o.number=true
-- 设置行会导致输入指令后乱码...
-- vim.o.lines=60
vim.opt.mouse="a"
vim.o.cursorline=true
vim.opt.laststatus=2
vim.o.autoindent=true
vim.opt.tabstop=4
vim.o.smarttab=true
vim.opt.shiftwidth=4
vim.opt.softtabstop=4
vim.opt.backspace="eol,start,indent"
vim.o.showcmd=true
vim.o.whichwrap=vim.o.whichwrap.."<,>,h,l"
vim.opt.scrolloff=3
vim.opt.history=1000
vim.opt.cmdheight=2


require'nvim-tree'.setup {
}
return require('plugins')
```

### PR DESCRIPTION
**Pull request by alex-courtis**
closes #1221

- detect `WinSeparator`, falls back to `VertSplit`
- `NvimTreeWinSeparator` defaults to `NvimTreeVertSplit`

We could put a warning about this deprecation however I do not think it is worth it.

### CODE REVIEW

File: lua/nvim-tree/colors.lua [hunk 1]
```diff
@@ -65,6 +65,7 @@ local function get_links()
     EndOfBuffer = "EndOfBuffer",
     CursorLine = "CursorLine",
     VertSplit = "VertSplit",
+    WinSeparator = "NvimTreeVertSplit",
```
Comment (alex-courtis) [inline lua/nvim-tree/colors.lua:68]: This is fine. `WinSeparator` defaults to `VertSplit` in 0.7.0.

**Comment by alex-courtis** [comment]
@siduck please test.

File: doc/nvim-tree-lua.txt [hunk 2]
```diff
@@ -872,11 +872,12 @@ NvimTreeWindowPicker
...
-EndOfBuffer
-CursorLine
-VertSplit
-CursorColumn
+NvimTreeNormal
+NvimTreeEndOfBuffer
+NvimTreeCursorLine
+NvimTreeVertSplit (deprecated, use NvimTreeWinSeparator)
+NvimTreeWinSeparator
+NvimTreeCursorColumn
```
Comment (alex-courtis) [inline doc/nvim-tree-lua.txt:880]: Not sure why there were no `NvimTree` prefixe. We can remove.

**Comment by siduck** [comment]
> @siduck please test.

works as expected 

image

**Comment by alex-courtis** [comment]
Thank you.

**Comment by par4m** [comment]
This works just fine, this might be unrelated but i can't figure out whats causing the horizontal split to go out of bounds, any idea?
image

**Comment by siduck** [comment]
> This works just fine, this might be unrelated but i can't figure out whats causing the horizontal split to go out of bounds, any idea? image

this seems like an upstream issue and I get it only when a horizontal splt's touching nvimtree.

**Comment by alex-courtis** [comment]
> this seems like an upstream issue and I get it only when a horizontal splt's touching nvimtree.

Could you try and replicate that without nvim-tree?

**Comment by siduck** [comment]
> > this seems like an upstream issue and I get it only when a horizontal splt's touching nvimtree.
> 
> Could you try and replicate that without nvim-tree?

with nvim-tree

image

without nvimtree

image

**Comment by adastx** [comment]
2022-05-03-130421_1745x1107_scrot

All works fine for me except for the horizontal splt's touching nvimtree as mentioned by the others.

**Comment by siduck** [comment]
numberwidth option ig

**Comment by alex-courtis** [comment]
> All works fine for me except for the horizontal splt's touching nvimtree as mentioned by the others.

That is a possible nvim-tree problem. I cannot replicate with the minimal config and `:hi NvimTreeVertSplit guibg=#ff0000 guifg=#00FF00`. I can see that there is a lot of customisation and probably plugins in your setup.

@siduck @adastx : please produce a minimal configuration that demonstrates this issue so that we may replicate: raise a new [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose) and put your minimal configuration in there.

**Comment by siduck** [comment]
@alex-courtis 
image

**Comment by siduck** [comment]
Steps to reproduce @alex-courtis 

```shell
git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```

My minimal config 

```lua
vim.opt.laststatus= 3
vim.opt.termguicolors = true

vim.cmd "hi Normal guibg=#000000"
vim.cmd "hi NvimTreeNormal guibg=#ffffff guifg=#000000"

vim.cmd "hi WinSeparator guibg='NONE'"
vim.cmd "hi NvimTreeWinSeparator guifg='#ffffff' guibg='#ffffff'"

require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
              "kyazdani42/nvim-tree.lua",
              branch = "1221-handle-deprecated-VertSplit",
      },
      "kyazdani42/nvim-web-devicons",
    },
 }
require("nvim-tree").setup {}
```

**Comment by alex-courtis** [comment]
> Steps to reproduce @alex-courtis

Replicated.

**Comment by alex-courtis** [comment]
Replicated without nvim-tree:

```
nvim --clean
<C-w>v
<C-w>w
<C-w>s
:set laststatus=3
:hi MyWinSeparator ctermfg=1 ctermbg=2
:setlocal winhl=WinSeparator:MyWinSeparator
```

[asciicast](https://asciinema.org/a/492738)

I don't know if this is intended behaviour; @siduck please raise a neovim issue.

**Comment by siduck** [comment]
@alex-courtis yes it is, So this is no longer nvimtree related issue Ig

File: doc/nvim-tree-lua.txt (hunk 2 above)
Comment (kyazdani42) [reply doc/nvim-tree-lua.txt:880]: I think it was because i've specified the original groups, but it doesn't matter too much, i actually think it's clearer this way

**Review by kyazdani42 — APPROVED** [review]
good enough for now, once we merge the switch to 0.7, we'll remove this :)
