### PR TITLE
fix(view): Recreate tree buffer if deleted, and handle scenario where buffer already exists.

### LINKED ISSUE #296: Session Restore Problems
Hello,

Initially, thank you for your continuous work on this beautiful approach to file explorer.

I have recently started to encounter problems with session management after the commit sha `bbb8d60`. When I load it with `nvim .` the nvim-tree works fine but when I save that session and reload it, it throws out a buffer id unknown error (not always) and just toggles a split of the current buffer. I have searched through the issues but this buffer id unknown seems to be a rather old issue [here](https://github.com/kyazdani42/nvim-tree.lua/issues/175) which might be unrelated.

### PR DESCRIPTION
**Pull request by sindrets**
Fixes #296.

This makes the tree able to recover when the tree buffer gets deleted or wiped. It also tackles scenarios where the NvimTree buffer already exists before initialization, as a result of i.e. a session being loaded. This is what I believe is the root of the problems described in 296.

### CODE REVIEW

**Comment by sindrets** [comment]
This seems to fix the problems described in 296, but I need to test this more thoroughly.

File: lua/nvim-tree/view.lua [hunk 1]
```diff
@@ -66,17 +66,60 @@ M.View = {
...
+      and a.nvim_buf_get_var(M.View.bufnr, "nvim_tree_buffer_ready") == 1
+      )
+  end)
+
+  if not success then
+    return false
+  else
+    return valid
+  end
+end
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:96]: i think you could just return `a.nvim_buf_is_valid(M.View.bufnr) and a.nvim_buf_is_loaded(M.View.bufnr)`

File: lua/nvim-tree/view.lua [hunk 2]
```diff
@@ -66,17 +66,60 @@ M.View = {
...
+
 -- set user options and create tree buffer (should never be wiped)
 function M.setup()
   M.View.auto_resize = vim.g.nvim_tree_auto_resize or M.View.auto_resize
   M.View.side = vim.g.nvim_tree_side or M.View.side
   M.View.width = vim.g.nvim_tree_width or M.View.width
 
   M.View.bufnr = a.nvim_create_buf(false, false)
+
+  if not pcall(a.nvim_buf_set_name, M.View.bufnr, 'NvimTree') then
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:106]: can you not set the same name for 2 buffers ?

File: lua/nvim-tree/view.lua [hunk 3]
```diff
@@ -66,17 +66,60 @@ M.View = {
...
+    -- Find the pre-existing NvimTree buffer, delete its windows then wipe it.
+    local bn = find_rogue_buffer()
+    if bn then
+      local win_ids = a.nvim_eval("win_findbuf(" .. bn .. ")")
+      for _, id in ipairs(win_ids) do
+        a.nvim_win_close(id, true)
+      end
+      a.nvim_command("bw " .. bn)
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:114]: use `a.nvim_buf_delete`

**Comment by kyazdani42** [comment]
i was going to do it but thanks for doing it first :)

File: lua/nvim-tree/view.lua (hunk 1 above)
Comment (sindrets) [reply lua/nvim-tree/view.lua:96]: Ah, right. That's better. I'm too used to the vim script way.

File: lua/nvim-tree/view.lua (hunk 2 above)
Comment (sindrets) [reply lua/nvim-tree/view.lua:106]: See, I didn't think that was a problem either, but try it. It throws `Vim:E95: Buffer with this name already exists`.

File: lua/nvim-tree/view.lua (hunk 3 above)
Comment (sindrets) [reply lua/nvim-tree/view.lua:114]: Nice. Again, I'm too stuck in the vim script headspace, where "delete" and "wipe" do not mean the same thing.

File: lua/nvim-tree/view.lua (hunk 2 above)
Comment (kyazdani42) [reply lua/nvim-tree/view.lua:106]: ha didn't know, good to know :)

File: lua/nvim-tree/view.lua (hunk 3 above)
Comment (kyazdani42) [reply lua/nvim-tree/view.lua:114]: no worries :) i've always hated vimscript and learned neovim development alltogether with lua and its api so it's easier for me to think that way

**Comment by sindrets** [comment]
This seems to work quite well on my end. So if we can get some of the people over in 296 to test this, I think we're good to go.

File: lua/nvim-tree/view.lua [hunk 4]
```diff
@@ -66,17 +66,52 @@ M.View = {
...
+local function is_buf_valid()
+  return a.nvim_buf_is_valid(M.View.bufnr) and a.nvim_buf_is_loaded(M.View.bufnr)
+end
+
+---Find pre-existing NvimTree buffer, delete its windows then wipe it.
+---@private
+function M._wipe_rogue_buffer()
+  local bn = find_rogue_buffer()
+  if bn then
+    local win_ids = a.nvim_eval("win_findbuf(" .. bn .. ")")
```
Comment (kyazdani42) [inline lua/nvim-tree/view.lua:91]: `vim.fn.win_findbuf`

**Review by kyazdani42 — CHANGES_REQUESTED** [review]
almost :D

File: lua/nvim-tree/view.lua (hunk 4 above)
Comment (sindrets) [reply lua/nvim-tree/view.lua:91]: Wow, I was just looking for this, and it didn't show up on tab completion for me so I didn't realize it was implemented.

**Comment by Shatur95** [comment]
> This seems to work quite well on my end. So if we can get some of the people over in 296 to test this, I think we're good to go.

Tested, works as expected!

File: lua/nvim-tree/view.lua (hunk 4 above)
Comment (kyazdani42) [reply lua/nvim-tree/view.lua]: most of the time, you can just try it `:lua vim.fn.win_findbuf()` and it will crash saying either the function doesn't exist or the function misses parameters :)

**Comment by kyazdani42** [comment]
thanks again !
