### PR TITLE
fix(lib): Refresh tree if it was opened before init.

### LINKED ISSUE #383: Tree empty if entering quickly after starting neovim
This is split from the discussions in #280.

I do not use packer lazy loading for nvim-tree. Yet, when starting neovim and quickly entering the tree (with a leader mapping), the tree is often initially empty and I have to re-toggle or refresh it to get contents.

image

This was the result of starting neovim and directly afterwards using my leader mapping leader-n. Setting debug="throw" did not surface anything.

My config is available here: https://github.com/languitar/config-nvim

Neovim is compiled daily and the plugins are updated along with that.

### PR DESCRIPTION
**Pull request by sindrets**
Fixes #383.

### CODE REVIEW

File: lua/nvim-tree/lib.lua [hunk 1]
```diff
@@ -34,6 +34,8 @@ function M.init(with_open, with_reload)
 
   if with_open then
     M.open()
+  elseif (view.win_open()) then
```
Comment (kyazdani42) [inline lua/nvim-tree/lib.lua:37]: could you just remove the parens around the condition to keep the codestyle please ?

**Review by kyazdani42 — CHANGES_REQUESTED** [review]

**Review by kyazdani42 — APPROVED** [review]
thanks man :)
